AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My Daily Log App backend infrastructure

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x

Resources:
  LogApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-daily-log-app
      Handler: lambda.handler
      CodeUri: .
      Environment:
        Variables:
          S3_BUCKET_NAME: my-daily-log-files
          DYNAMODB_TABLE_NAME: DailyLogEvents
      Policies:
        - Version: "2012-10-17"
          Statement:
            # S3: Only allow access to your specific bucket and its objects
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::my-daily-log-files
                - arn:aws:s3:::my-daily-log-files/*
            # DynamoDB: Only allow access to your specific table and its indexes
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
              Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/DailyLogEvents
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/DailyLogEvents/index/userSub-index
            # Allow Lambda basic execution (logs)
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "arn:aws:logs:*:*:*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-daily-log-files
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  LogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DailyLogEvents
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userSub
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userSub-index
          KeySchema:
            - AttributeName: userSub
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
